Misc sd kfixes
LootLocker/unreal-sdk pull request #14
Opened 2022-10-17 06:42 UTC by gitvestman

Added missing implementations for
WhiteLabelVerifySession
WhiteLabelRequestUserVerification
WhiteLabelRequestPasswordReset
GetAllMemberRanks
LookupMultiplePlayerNamesUsingIDs
LookupMultiplePlayerNames1stPlatformIDs

Corrected implementations for
GetUniversalAssets
GetOtherPlayersXpAndLevel

Could not test everything

2022-10-18 13:11 UTC, kirre-bylund requested changes

2022-10-18 13:11 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerAssetsRequestHandler.cpp
> +    if (After != -1)
I imagine this should be <0 no?

2022-10-18 13:11 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerLeaderboardRequestHandler.cpp
> +    if (GetAllMemberRanksRequests.after != -1)
Should this not be <0?

2022-10-18 13:11 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerPlayerRequestHandler.cpp
> +		QueryParams.Add(player.platform, player.player_id);
From what I can tell this is misleading. You're reusing the "MultiplePlayerNamesRequest" which takes as "keys" platforms f.ex. But this endpoint wants only either "player_id=<number>" or "player_public_uid=<string>". So probably should have its own Request class, or simply take an array of longs/strings or similar and we fill in the "player_id" and "player_public_uid" parts.

2022-10-18 13:11 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +    *  https://ref.lootlocker.com/game-api/#request-reset-password
I think you updated the documentation on the wrong method

2022-10-18 13:11 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerAuthenticationRequestHandler.cpp
> +	VerifyRequest.token = ULootLockerPersistentDataHolder::Token;
There is a use case for the token being supplied as a parameter. Users can make their own handling of sessions etc. That is at least the case in the Unity SDK. Maybe have 1 method that takes the token as well and make this method call that after picking the token from DataHolder?

2022-10-18 14:03 UTC, gitvestman commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerAssetsRequestHandler.cpp
> +    if (After != -1)
I copied some other method but < 0 should work for all

2022-10-18 14:06 UTC, gitvestman commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerAssetsRequestHandler.cpp
> +    if (After != -1)
or >= 0

2022-10-18 14:26 UTC, gitvestman commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerAuthenticationRequestHandler.cpp
> +	VerifyRequest.token = ULootLockerPersistentDataHolder::Token;
The token is set in all API request like this so that would probably require some redesign
Request->SetHeader(TEXT("x-session-token"), ULootLockerPersistentDataHolder::Token);

2022-10-25 09:55 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerPlayerRequestHandler.cpp
> +		QueryParams.Add(player.platform, player.player_id);
Fixed

2022-10-28 13:07 UTC, kirre-bylund reviewed
All outstanding remarks dealt with

2022-10-28 13:07 UTC, kirre-bylund approved these changes

2022-10-28 13:12 UTC, JohannesLoot commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +     static void GetOtherPlayersXpAndLevel(FString OtherPlayerId, const FPOtherPlayersXpAndLevelBP& OnGetOtherPlayersXpAndLevelRequestCompleted, FString OtherPlayerPlatform = FString(TEXT("")));
Not a fan of this being an Fstring, since it requires you to write the platform. Not something we need to fix now maybe, but make sure to add a trello-task for it if we keep it like this.

2022-10-28 13:19 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +     static void GetOtherPlayersXpAndLevel(FString OtherPlayerId, const FPOtherPlayersXpAndLevelBP& OnGetOtherPlayersXpAndLevelRequestCompleted, FString OtherPlayerPlatform = FString(TEXT("")));
Do you mean you'd like it as an enum, or how do you mean?

2022-10-28 14:14 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +     static void GetOtherPlayersXpAndLevel(FString OtherPlayerId, const FPOtherPlayersXpAndLevelBP& OnGetOtherPlayersXpAndLevelRequestCompleted, FString OtherPlayerPlatform = FString(TEXT("")));
Discussed this elsewhere and decided to make a ticket for changing platform handling to an enum in the SDK core later and do this then.

2022-10-28 14:14 UTC, merged