Added feedback
lootlocker/unreal-sdk pull request #171
Opened 2024-07-24 08:59 UTC by AlmightyMikkel

2024-07-27 12:54 UTC, kirre-bylund requested changes

2024-07-27 12:54 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +    * @param Type: Is the Category Type you want to list (Player, UGC, Game)
```suggestion
    * @param Type Is the Category Type you want to list (Player, UGC, Game)
```

2024-07-27 12:54 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Public/LootLockerSDKManager.h
> +
Unintended change?

2024-07-27 12:54 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerFeedbackRequestHandler.cpp
> +FString ULootLockerFeedbackRequestHandler::FeedbackTypeEnumToString(ELootLockerFeedbackType e)
This is not necessary, there's already a generic method for enum to string: https://github.com/lootlocker/unreal-sdk/blob/main/LootLockerSDK/Source/LootLockerSDK/Private/Utils/LootLockerUtilities.cpp#L17

2024-07-27 12:54 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Public/LootLockerSDKManager.h
> +    static void SendGameFeedback(const FString& Ulid, const FString& Description, const FString& CategoryID, const FLootLockerSendFeedbackResponseDelegate& OnComplete)
Why does this take a ULID in Unreal but not Unity?

2024-08-02 14:19 UTC, AlmightyMikkel commented on LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerFeedbackRequestHandler.cpp
> +FString ULootLockerFeedbackRequestHandler::FeedbackTypeEnumToString(ELootLockerFeedbackType e)
Oh my lord thank you, I was going insane because of this!

2024-08-02 14:20 UTC, AlmightyMikkel commented on LootLockerSDK/Source/LootLockerSDK/Public/LootLockerSDKManager.h
> +    static void SendGameFeedback(const FString& Ulid, const FString& Description, const FString& CategoryID, const FLootLockerSendFeedbackResponseDelegate& OnComplete)
I missed removing it after agreeing with Kamran that we shouldn't include a ULID. Will fix!

2024-08-14 07:00 UTC, kirre-bylund commented
I'm confused... You resolve the comments but I don't see any more commits that fixes what you agree with?

2024-08-19 06:13 UTC, kirre-bylund requested changes

2024-08-19 06:13 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerManager.cpp
> +void ULootLockerManager::ListPlayerFeedbackCategory(const FLootLockerListFeedbackCategoryResponseBP& OnComplete)
The list categories should still be plural

2024-08-19 06:13 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerFeedbackRequestHandler.cpp
> +}
I thought you said you'd remove this and use the general one instead? Is it that you marked the comment as resolved before you fixed it and now missed it?

2024-08-19 06:13 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +    * Get a list of Categories to use for feedback, this can be anything from reporting players, ugc, or giving feedback such as nice notes about a UGC
Comment is now wrong. This is only for player

2024-08-19 06:13 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +    * @param Type: Is the Category Type you want to list (Player, UGC, Game)
Type is not a parameter anymore.

2024-08-19 06:13 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Public/LootLockerManager.h
> +    static void ListUGCFeedbackCategory(const FLootLockerListFeedbackCategoryResponseBP& OnComplete);
Descriptions are wrong

2024-08-19 13:15 UTC, kirre-bylund approved these changes

2024-08-20 05:51 UTC, merged