Add support for Triggers 2.0
lootlocker/unreal-sdk pull request #183
Opened 2024-10-09 08:19 UTC by kirre-bylund

2024-10-10 06:19 UTC, JohannesLoot commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerGameEndpoints.cpp
> +FString ULootLockerGameEndpoints::GameBaseUrl = "https://{domainKey}api.stage.internal.dev.lootlocker.cloud/game/";
Nope!

2024-10-10 06:22 UTC, JohannesLoot requested changes
You accidentally commited the stage-url, change that before merging.
Other than that, all good!

2024-10-14 06:53 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerGameEndpoints.cpp
> +FString ULootLockerGameEndpoints::GameBaseUrl = "https://{domainKey}api.stage.internal.dev.lootlocker.cloud/game/";
Fixed

2024-10-14 06:54 UTC, JohannesLoot approved these changes
All good! ✔️

2024-10-14 16:14 UTC, merged