Bring branch to parity with Blue Scarab fixes and address warnings
LootLocker/unreal-sdk pull request #27
Opened 2022-11-04 09:52 UTC by kirre-bylund

**Blue Scarab Pull Requests**
https://github.com/LootLocker/unreal-sdk/pull/12
https://github.com/LootLocker/unreal-sdk/pull/9
https://github.com/LootLocker/unreal-sdk/pull/8

I've gone through them commit by commit and added all the fixes that had not been addressed on the v2 branch. The only thing I have not brought in is the Guest Login addition as that is part of a larger discussion on how to handle platforms vs authentication methods in the sdks. In PR 8 see commits 
bac02afa890a4141c22322a798fbe99f742108b5 - sync project to plugin
e51468687b5c76a2b41da5dc834748df6c3a37a1 - Guest Login

** Template **
In June the file LootLockerTemplates.h was added to the public facing part of the v2 branch but never updated nor used anywhere. Until I know why and what it's for I have removed it.

**Compilation Warnings**
I went through and fixed a bunch of warnings in the project:
* "Uninitialized" - not initializing stuff in C++ is bad. So I fixed a slew of those problems where I found them.
* "Auto doesn't catch references, unintended copy" - the auto keyword just deduces the underlying type and if not used as "auto&" it will make a copy of the object which is stupid for for loops for example.
* "Intended bitwise comparison?" - We're checking if the map is empty and the NOT was in the wrong place causing this warning. I wanted to switch it out to an "IsEmpty" but that wasn't available in earlier C# versions.

2022-11-04 10:04 UTC, TobiasBerg requested changes

2022-11-04 10:04 UTC, TobiasBerg commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerHeroRequestHandler.cpp
> +	LLAPI<FLootLockerHeroLoadoutResponse>::CallAPI(HttpClient, FLootLockerHeroAssetInstance{ AssetInstanceID }, ULootLockerGameEndpoints::RemoveAssetToHeroLoadout,  { HeroID },EmptyQueryParams,OnComplet
There's some weird spacing for parameters here

2022-11-04 10:04 UTC, TobiasBerg commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerConfig.h
> -	GoG = 3					UMETA(DisplayName = "GoG")
I would remove GoG completely

2022-11-04 10:04 UTC, TobiasBerg commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerConfig.h
> -	EpicStore = 3			UMETA(DisplayName = "EpicStore"),
I would remove EpicStore completely

2022-11-04 10:06 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerConfig.h
> -	EpicStore = 3			UMETA(DisplayName = "EpicStore"),
Fixed

2022-11-04 10:06 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Public/LootLockerConfig.h
> -	GoG = 3					UMETA(DisplayName = "GoG")
Fixed

2022-11-04 10:08 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/GameAPI/LootLockerHeroRequestHandler.cpp
> +	LLAPI<FLootLockerHeroLoadoutResponse>::CallAPI(HttpClient, FLootLockerHeroAssetInstance{ AssetInstanceID }, ULootLockerGameEndpoints::RemoveAssetToHeroLoadout,  { HeroID },EmptyQueryParams,OnComplet
Fixed

2022-11-07 07:09 UTC, JohannesLoot reviewed
Do we need to test any of the changes from Blue Scarab before merging this?

2022-11-08 07:12 UTC, kirre-bylund commented on v2/LootLockerSDK/Source/LootLockerSDK/Private/Utils/LootLockerUtilities.h
> +        UE_LOG(LogLootLockerGameSDK, Log, TEXT("Request:"));
Should still log these on error as warn.

2022-11-08 07:15 UTC, kirre-bylund commented
> Do we need to test any of the changes from Blue S

The answer to "Do we need to test the changes" should always be yes. But it's a bit tricky as it's mostly just warning fixes all over the place so what you'd need is a full regression test. Would have been satisfied with CI tests if we had any. So under the circumstances I'd say no. If we still want to do any then I'd say; do some spot checks on some flows, and then test the missions one as that has the most significant changes?

2022-11-08 13:50 UTC, TobiasBerg approved these changes

2022-11-08 17:17 UTC, merged