Update LootLockerSDK settings
LootLocker/unreal-sdk pull request #58
Opened 2023-01-27 10:33 UTC by kirre-bylund

* Deprecate Platform dropdown but leave it in for legacy
* Add tooltips and change naming to clarify api keys etc.
* Make development mode legacy and make it conditional on if there's a legacy api key.

2023-02-01 06:56 UTC, JohannesLoot commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerPlatformManager.cpp
> +void ULootLockerCurrentPlatform::Set(const ELootLockerPlatformType& LegacyPlatform)
I'm not entirely sure that we can swap Android for Guest. It works with authentication, but for purchasing, Android is still a platform. So we might need to be able to set Android as a platform to be able to do purchases.

2023-02-01 07:01 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerPlatformManager.cpp
> +void ULootLockerCurrentPlatform::Set(const ELootLockerPlatformType& LegacyPlatform)
Interesting, let's investigate. The same should go for the change in the Unity SDK in that case

2023-02-01 12:43 UTC, TobiasBerg requested changes

2023-02-01 12:43 UTC, TobiasBerg commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerPlatformManager.cpp
> +void ULootLockerCurrentPlatform::Set(const ELootLockerPlatformType& LegacyPlatform)
Android and guest are not the same in the backend, players are treated in different buckets, so we should support them both. 

Just for information though, the current Android platform will soon be deprecated, and a new Google Sign In will be added as well. 
We we still need to support the old platform, for the games already using it.

2023-02-01 13:01 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerPlatformManager.cpp
> +void ULootLockerCurrentPlatform::Set(const ELootLockerPlatformType& LegacyPlatform)
✅ I understood you the complete reverse when we had the prep chat 😂 I'll fix it (and in the Unity SDK as well)

2023-02-03 16:02 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerPlatformManager.cpp
> +void ULootLockerCurrentPlatform::Set(const ELootLockerPlatformType& LegacyPlatform)
Fixed now

2023-02-07 12:39 UTC, TobiasBerg approved these changes

2023-02-07 13:02 UTC, merged