Add StartGoogleSession method
LootLocker/unreal-sdk pull request #71
Opened 2023-02-20 11:01 UTC by kirre-bylund

2023-02-28 13:21 UTC, kristijan-ujevic commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerManager.cpp
> +
I would do these as overloads, one with the refresh token param and one without

2023-02-28 13:30 UTC, kristijan-ujevic requested changes

2023-02-28 13:30 UTC, kristijan-ujevic commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerSDKManager.cpp
> +
I would do these as overloads, one with the refresh token param and one without

2023-02-28 15:48 UTC, kirre-bylund commented on LootLockerSDK/Source/LootLockerSDK/Private/LootLockerSDKManager.cpp
> +
Fixed

2023-03-01 09:19 UTC, kristijan-ujevic approved these changes

2023-03-01 09:48 UTC, merged